name: Nightly builds

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
            bundle: ""
          - arch: x86_64
            runs-on: ubuntu-24.04
            bundle: ""
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
            bundle: ffmpeg
          - arch: x86_64
            runs-on: ubuntu-24.04
            bundle: ffmpeg
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install -U --upgrade-strategy=eager -r requirements.txt
      - name: Build
        run: |
          SOURCE_DATE_EPOCH=$(git show -s --format=%ct) ./build.sh --gitref=master --bundle=${{ matrix.bundle }}
      - name: Get file name
        id: vars
        run: |
          echo "file_name=$(cd dist && ls *.*)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.file_name }}
          path: dist/*
